<a href="https://colab.research.google.com/github/arrowstoflight/AI/blob/master/HW_4/HW4_Problem1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dustin White

CAP4630 - Artificial Intelligence

Professor Wocjan

5 April 2020

Homework 4


# Problem 1



Using only ```numpy```, implement the function ```conv2d```.  It takes as input ```input_mat``` and ```kernel_mat``` and outputs ```output_mat```.  All variables 
are square matrices.  It should compute the convolution of ```input_mat``` with the kernel ```kernel_mat``` using valid padding.

Note that the size ```s``` of the kernel matrix can also be an even number.  

```
input matrix

 0  1  2  3  4 

 5  6  7  8  9
 
 0  1  2  3  4 
 
 5  6  7  8  9
 
 0  1  2  3  4 

a) indicates the very first position in which a 2 x 2 filter is placed in the above 5 x 5 input matrix

+----+
|0  1| 2  3  4 
|    |
|5  6| 7  8  9
+----+
 0  1  2  3  4 

 5  6  7  8  9
 
 0  1  2  3  4 

b) indicates the very first position in which a 3 x 3 filter is placed in the above 5 x 5 input matrix

+-------+
|0  1  2| 3  4 
|       |
|5  6  7| 8  9
|       |
|0  1  2| 3  4 
+-------+
 5  6  7  8  9
 
 0  1  2  3  4 
```



In [0]:
import numpy as np

class nonSquareError(Exception):
  # matrix is the passed matrix | Code is used to determine if input or kernel matrix
  def __init__(self, matrix, code):
    # Input Matrix Error
    if(code == 0):
      print("Input Matrix Non-Square: Row(s) " + str(matrix.shape[0]) + " != Column(s) " + str(matrix.shape[1]))
    # Kernel Matrix Error
    else:
      print("Kernel Matrix Non-Square: Row(s) " + str(matrix.shape[0]) + " != Column(s) " + str(matrix.shape[1]))

class kernelTooBigError(Exception):
  def __init__(self, matrixA, matrixB):
    print("Kernel matrix is " + str(matrixB.shape[0]) + " which is > the input matrix: " + str(matrixA.shape[0]))

def computeKernel(input_mat, kernel_mat, row, col):
  value = 0;
  kernelSize = kernel_mat.shape[0]

  for i in range(0, kernelSize):
    for j in range(0, kernelSize):
      value += kernel_mat[i][j]*input_mat[i + row][j + col] 
  return value;

def conv2d(input_mat, kernel_mat):
  if(input_mat.shape[0] != input_mat.shape[1]):
    raise nonSquareError(input_mat, 0)
  if(kernel_mat.shape[0] != kernel_mat.shape[1]):
    raise nonSquareError(kernel_mat, 1)
  if(kernel_mat.shape[0] > input_mat.shape[0]):
    raise kernelTooBigError(input_mat, kernel_mat)

  # The Output Size is (input size - kernel size +)
  size = input_mat.shape[0] - kernel_mat.shape[0] + 1
  #print("Output Size: " + str(size) + "x" + str(size))

  kSize = kernel_mat.shape[0]

  # Flip the kernel
  rotated_mat = np.zeros((kSize, kSize))
  rotated_mat = np.rot90(kernel_mat,2)

  # creates output matrix the size of the kerel_mat
  output_mat = np.zeros((size,size))
  # stores the targeted kernel into output_mat
  for i in range(0, size):
    for j in range(0, size):
      compute = computeKernel(input_mat, rotated_mat, i, j)
      output_mat[i][j] = compute

  #print("input Matrix:\n" + str(input_mat))
  return output_mat

## Test Cases

In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

Kernel matrix is 4 which is > the input matrix: 2


kernelTooBigError: ignored

# Problem 2


Using only ```numpy```, implement the function ```maxpooling2d```. It takes as input ```input_mat``` and ```s``` and outputs ```output_mat```.
The variables ```input_mat``` and ```output_mat``` are square matrices and ```s``` is an integer.  It should compute the maxpooling operation 
on ```input_mat``` using window of shape ```s``` times ```s```.

---

Make sure that you throw appropriate custom exceptions indicating the problem when the operations in Problem 1 and Problem 2 cannot be performed. 

The test cases are in [test_cases_for_problems_1_2_homework_4.ipynb](https://colab.research.google.com/drive/1MIoNq4_xglLesBF1kdWJelP2CmdPuYbv).

---

In [0]:
import numpy as np

class nonSquareError(Exception):
  # matrix is the passed matrix | Code is used to determine if input or kernel matrix
  def __init__(self, matrix):
    print("Input Matrix Non-Square: Row(s) " + str(matrix.shape[0]) + " != Column(s) " + str(matrix.shape[1]))

class kernelTooBigError(Exception):
  def __init__(self, matrixSize, s):
    print("Window S size is " + str(s) + " which is > the input matrix size: " + str(matrixSize))

def computeMaxPool(input_mat, s, x, y):
  maxVal = 0;
  iSize = input_mat.size[0];

  for i in range(0, s):
    for j in range(0, s):
      if(i + x < iSize and j + y < iSize):
        temp = input_mat[i + x][j + y]
        if(maxVal < temp):
          maxVal = temp 

  return maxVal  


def maxpooling2d(input_mat, s):
  if(input_mat.shape[0] != input_mat.shape[1]):
    raise nonSquareError(input_mat)
  if(s > input_mat.shape[0]):
    raise kernelTooBigError(input_mat.shape[0], s)

  iSize = input_mat.shape[0]; 
  output_mat = np.zeros((s,s))

  for i in range(0, iSize, s):
    for j in range(0, iSize, s):
      compute = computeMaxPool(input_mat, s, i, j)
      output_mat[int(i/2)][int(j/2)] = compute
  return output_mat

## Test Cases

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  #output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
