<a href="https://colab.research.google.com/github/arrowstoflight/AI/blob/master/HW_1/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dustin White

CAP4630 - Artificial Intelligence

Professor Wocjan

20 January 2020

Multiply Numpy Matrices 

In [0]:
import numpy as np

class MatrixError(Exception):
  def __init__(self, matrixA, matrixB):
    self.matrixA = matrixA
    self.matrixB = matrixB
    print("Error: Matrix A Columns are not equal to Matrix B\nMatrix A:\n" + str(matrixA) + "\nMatrix B:\n" + str(matrixB))
    print("Column: " + str(matrixA.shape[1]) + " != Row: " + str(matrixB.shape[0]))

class EmptyListError(Exception):
  def __init__(self, matrix):
    self.matrix = matrix
    print("Error: Passed an empty list")


# row x column; in order to multiply: colA must equal row B
def check_matrices(a, b):
  if(a.shape[1] == b.shape[0]):
    return True
  else:
    raise MatrixError(a,b)
    return False

# Problem - Sequentially Multiply a List of Numpy Arrays [$M_1$,M2,M3,...,MN]
def multiply_matrices(q):
  length = len(q)

  # Check to see if we are passed an empty list
  if len(q) == 0:
     raise EmptyListError(q)
     return q
  # If the length is 1 just return it  
  if len(q) == 1:
    return q
  # If we are passed 2 matrices then multiply them and return
  elif len(q) == 2:
    newMatrixA = q.pop(0)
    newMatrixB = q.pop(0)
    check_matrices(newMatrixA,newMatrixB)
    return np.matmul(newMatrixA, newMatrixB)

  # Else Start the multiplication chain
  newMatrixA = q.pop(0)
  newMatrixB = q.pop(0)
  check_matrices(newMatrixA,newMatrixB)
  newMatrixResult = np.matmul(newMatrixA, newMatrixB)
  # Continue multiplying till we get to the end of the list
  while (len(q) != 0):
    newMatrixB = q.pop(0)
    check_matrices(newMatrixResult,newMatrixB)
    newMatrixResult = np.matmul(newMatrixResult, newMatrixB)

  return newMatrixResult

# Main
a = np.array([[1, 2],[3, 4],[6,6]])
b = np.array([[2, 3],[4,5]])
c = np.array([[3, 4, 1, 1],[5, 6, 1, 1],[3, 4, 1, 1]])
d = np.array([[4, 5],[6,7]])
x = [a,b,d]
y = [a,b,c]
z = []

# EXAMPLE 1 - Correct Multiplication
try:
  # Run the function and store it in answer
  answerX = multiply_matrices(x)
except MatrixError as e:
  pass
except EmptyListError as e:
  pass
else:
  print("Multiplication answer: \n" + str(answerX))
print("\n\n")

# EXAMPLE 2 - Incompatible Matrices
try:
  # Run the function and store it in answer
  answerY = multiply_matrices(y)
except MatrixError as e:
  pass
except EmptyListError as e:
  pass
else:
  print("Multiplication answer: \n" + str(answerY))
print("\n\n")

# EXAMPLE 3 - Empty List
try:
  # Run the function and store it in answer
  answerZ = multiply_matrices(z)
except MatrixError as e:
  pass
except EmptyListError as e:
  pass
else:
  print("Multiplication answer: \n" + str(answerY))
print("\n\n")

Multiplication answer: 
[[118 141]
 [262 313]
 [432 516]]



Error: Matrix A Columns are not equal to Matrix B
Matrix A:
[[10 13]
 [22 29]
 [36 48]]
Matrix B:
[[3 4 1 1]
 [5 6 1 1]
 [3 4 1 1]]
Column: 2 != Row: 3



Error: Passed an empty list



