<a href="https://colab.research.google.com/github/arrowstoflight/AI/blob/master/HW_1/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
# Dustin White
# COP4520 - Machine Learning
# Professor Wocjan
# 20 January 2020
# Multiply Numpy Matrices 

import numpy as np
import sys

# row x column; in order to multiply: colA must equal row B
def check_matrices(a, b):
  if(a.shape[1] == b.shape[0]):
    return True
  else:
    ex = matrixError()
    ex.matrixA= a;
    ex.matrixB = b;
    raise ex
    return False

# Problem - Sequentially Multiply a List of Numpy Arrays [$M_1$,M2,M3,...,MN]
def multiply_matrices(q):
  length = len(q)

  # Check to see if we are passed an empty list
  if len(q) == 0:
     raise emptyListError
     return q
  # If the length is 1 just return it  
  if len(q) == 1:
    return q
  # If we are passed 2 matrices then multiply them and return
  elif len(q) == 2:
    newMatrixA = q.pop(0)
    newMatrixB = q.pop(0)
    check_matrices(newMatrixA,newMatrixB)
    return np.matmul(newMatrixA, newMatrixB)

  # Else Start the multiplication chain
  newMatrixA = q.pop(0)
  newMatrixB = q.pop(0)
  check_matrices(newMatrixA,newMatrixB)
  newMatrixResult = np.matmul(newMatrixA, newMatrixB)
  # Continue multiplying till we get to the end of the list
  while (len(q) != 0):
    newMatrixB = q.pop(0)
    check_matrices(newMatrixResult,newMatrixB)
    newMatrixResult = np.matmul(newMatrixResult, newMatrixB)

  return newMatrixResult

# Guess this is main?
a = np.array([[1, 2],[3, 4],[6,6]])
b = np.array([[2, 3],[4,5]])
c = np.array([[3, 4, 1, 1],[5, 6, 1, 1],[3, 4, 1, 1]])
d = np.array([[4, 5],[6,7]])
z = [a,b,c]
try:
  # Run the function and store it in answer
  answer = multiply_matrices(z)
except emptyListError:
  print("Error: Passed an empty list")
except matrixError as e:
  print("Error: Matrix A Columns are not equal to Matrix B\nMatrix A:\n" + str(e.matrixA) + "\nMatrix B:\n" + str(e.matrixB))
  print("\nColumn: " + str(e.matrixA.shape[1]) + " != Row: " + str(e.matrixB.shape[0]))
else:
  print(answer)

Error: Matrix A Columns are not equal to Matrix B
Matrix A:
[[10 13]
 [22 29]
 [36 48]]
Matrix B:
[[3 4 1 1]
 [5 6 1 1]
 [3 4 1 1]]

Column: 2 != Row: 3
